Example for reading shapefiles with GDAL and displaying the geometry.
AmonRaNet/QGeoView pull request #53
Opened 2024-05-19 15:51 UTC by OgreTransporter

I have used the simple Basic example and simply read in a shapefile. As in the layer example, I created a geometric drawing class - in this case a polygon - and used it to draw the contours from the file. To test this, I loaded the country file from Natural Earth (https://www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_0_countries.zip).

2024-05-22 20:26 UTC, AmonRaNet requested changes

2024-05-22 20:26 UTC, AmonRaNet commented on CMakeLists.txt
> +find_package(GDAL CONFIG)
Is any way to add GDAL also to qmake project?

2024-05-22 20:26 UTC, AmonRaNet commented on samples/shapefile/CMakeLists.txt
Maybe whole sample better to name more accurate - it is GDAL example. What about gdal-shapefile

2024-05-22 20:26 UTC, AmonRaNet commented on CMakeLists.txt
> +find_package(GDAL CONFIG)
Maybe example from here: https://github.com/chris5287/QWidgetMap/blob/master/src/Example/Example.pro

2024-05-23 18:51 UTC, OgreTransporter commented on samples/shapefile/CMakeLists.txt
Done

2024-06-04 22:26 UTC, AmonRaNet approved these changes

2024-06-04 22:27 UTC, AmonRaNet commented on CMakeLists.txt
> +find_package(GDAL CONFIG)
Fine - I will check then myself

2024-06-04 22:28 UTC, merged